### ISSUE TITLE
Failed to load implementation from

### ISSUE THREAD

**Issue by amitchandak** [fommil/matrix-toolkits-java#50]
Hi,
I downloaded the "zip" file from git repo and then tried to build the project using maven.
##  T E S T S

Running no.uib.cipr.matrix.LowerSymmDenseMatrixTest
Sep 05, 2014 1:43:11 PM com.github.fommil.netlib.BLAS <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
Sep 05, 2014 1:43:11 PM com.github.fommil.netlib.BLAS <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
Sep 05, 2014 1:43:11 PM com.github.fommil.netlib.LAPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
Sep 05, 2014 1:43:11 PM com.github.fommil.netlib.LAPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeRefLAPACK

[Other Test Cases Truncated]
Results :

Tests run: 2447, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.380 s
[INFO] Finished at: 2014-09-05T13:43:28+05:30
[INFO] Final Memory: 11M/292M
[INFO] ------------------------------------------------------------------------

How can I avoid these, since these are required for achieving best performance. 
Thank You,
Amit.

**Comment by ellbur** [comment]
For what it's worth, I got native netlib to work by including the [`breeze-natives`](https://github.com/scalanlp/breeze) package from Scala Breeze as a dependency. This might work even if you're not using Breeze. You could also look at what that package includes and see if you can copy it to get native libraries working.
