### ISSUE TITLE
make a new release on maven central

### ISSUE THREAD

**Issue by shilad** [fommil/matrix-toolkits-java#57]
Right now it looks like the only way to create a LinkedSparseMatrix is to write some other type of Matrix out to a file and read it back in. It would be convenient to have a constructor that takes another Matrix directly.

**Comment by fommil** [comment]
The constructor wouldn't really help, although I'm not sure why you think this needs to involve I/O. There is a constructor that takes the size and setters to build the matrix up.

The point is that all other formats would not be able to hold the matrix in memory and this is to enable creation from a stream. If you can construct another container then it probably means LinkedSparseMatrix is going to bring a significant performance hit.

**Comment by fommil** [comment]
e.g. by population from another sparse format:
https://github.com/fommil/matrix-toolkits-java/blob/master/src/test/java/no/uib/cipr/matrix/sparse/LinkedSparseMatrixTest.java#L33

**Comment by shilad** [comment]
Thanks for the pointer. I was actually trying to work off that example, but the constructors are protected. I worked around this for the moment by doing:

```java
Matrix m2 = new LinkedSparseMatrix(m) {};
```

**Comment by fommil** [comment]
err, that doesn't sound good. Maybe we should be making it `final` to avoid this :smile:. Why can't you just do this?

```java
  A = new LinkedSparseMatrix(n, m);
  Ad = Utilities.rowPopulate(A, nz);
```

**Comment by fommil** [comment]
What am I talking about, there is exactly what you need:

* https://github.com/fommil/matrix-toolkits-java/blob/master/src/main/java/no/uib/cipr/matrix/sparse/LinkedSparseMatrix.java#L198

although I admit it is not terribly useful. How come your IDE couldn't see this?

**Comment by shilad** [comment]
Aha! It looks like this was fixed on master in commit fcfdb8f81be9d153d52a7d7e2e70946d79df9081. I was working off the latest maven release (1.0.1), which still has these methods protected. Thanks for the pointer.

**Comment by fommil** [comment]
oh, maybe I should make a new release. Reopening to do so.

**Comment by shilad** [comment]
Thanks!

**Comment by fommil** [comment]
I'm looking into this, it should be done this weekend. Also cleaning up the CI.

**Comment by fommil** [comment]
I've staged 1.0.2, it should be on central shortly.

If you're planning on contributing, make sure to rebase... I did quite a lot of work on the travis CI and we now have coverage and code formatting enforcement rules (I've used it in other projects and it really helps just standardise everything).
