### ISSUE TITLE
License version?

### ISSUE THREAD

**Issue by hyandell** [fommil/matrix-toolkits-java#63]
Looking at the high level LICENSE file, the license of the project is LGPL 3.0. Every source file with a source header indicates that the licensing is LGPL 2.1.

Which version of the license is intended to apply? Asking because LGPL 3.0 involves much more discussion for me to get approval to use at work.

**Comment by fommil** [comment]
2.1 can use any later version. If it's an issue for you, consider it 2.1 for for use and refer back to this message as confirmation. :-) 

Interesting that 3.0 is harder for you. Can you please email me the name of the company, which I'll keep in confidence.
