### ISSUE TITLE
wrong exception message in AbstractMatrix.checkMultAdd(Matrix B, Matrix C)

### ISSUE THREAD

**Issue by maxxkia** [fommil/matrix-toolkits-java#69]
In the third assertion:
"if (B.numColumns() != C.numColumns())"

The expected error message thrown would be:
B.numColumns != C.numColumns (" + **B.numColumns()** + " != " + C.numColumns() + ")");

But, instead of **B.numColumns()** it is **B.numRows()** in the source code!

**Comment by fommil** [comment]
can you please link to the offending line? github supports that. Better yet, a pull request with a fix ;-)

**Comment by fommil** [comment]
oh I see it now https://github.com/fommil/matrix-toolkits-java/blob/master/src/main/java/no/uib/cipr/matrix/AbstractMatrix.java#L349

ok, please send a PR with the fix and I'll merge.
