### ISSUE TITLE
Estimate eigen vector using power iteration

### ISSUE THREAD

**Issue by srikanthBezawada** [fommil/matrix-toolkits-java#73]
Hello ,

I need to estimate the eigen vector by passing initial vector and a matrix just like the method here [1]. Is this method available for matrix-toolkits-java library ? Please let me know

[1] - https://github.com/algorithmfoundry/Foundry/blob/31685b9d2f3d4f0cb990c3c3de49ee2703743de1/Components/CommonCore/Source/gov/sandia/cognition/math/matrix/decomposition/EigenvectorPowerIteration.java#L251

**Comment by fommil** [comment]
not that I know of, but it might be. It seems like a bit of a toy algorithm, there are much better ways of doing it that you would learn about in any good numerical programming course.

**Comment by srikanthBezawada** [comment]
Hi Fommil,

Thanks for the quick response. Above method referenced takes stoppingThreshold, maxIterations  for numerical method. Actually what I need is a method which takes damping parameter as input instead of  stoppingThreshold, maxIterations .

 I need to achieve similar implementation as [here](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.link_analysis.pagerank_alg.pagerank_numpy.html) (i.e) Damping parameter for PageRank, default=0.85.

I am not confident of the numerical methods related to this context at the moment , so I'm considering to reuse  a library's implementation.

**Comment by fommil** [comment]
these kinds of algorithms have the feel of numerical optimisation rather (it all seems a sort of global or local search for a fit) than straight linear algebra so you might be best having a look at some machine learning libraries or something of that ilk?

**Comment by srikanthBezawada** [comment]
Thanks for the advice Fommil, I am looking up for the same.
