### ISSUE TITLE
Sparse SVD

### ISSUE THREAD

**Issue by nvx2004** [fommil/matrix-toolkits-java#88]
Do you have any plans to add sparse SVD functionality? I believe the package SVDPACK (http://netlib.org/svdpack/) might be of use. Unfortunately, I am not sure about how difficult this might be in terms of linking MTJ to SVDPACK similarly as LAPACK libraries have been linked to MTJ.

Thanks for considering this.

**Comment by fommil** [comment]
this would be a feature request for netlib-java and I'll save you the effort of telling you: only if you pay me to do it.
