### ISSUE TITLE
COO Matrix support.

### ISSUE THREAD

**Issue by Madder** [fommil/matrix-toolkits-java#90]
Probably not the right place to post this. But I'm wondering whether it's possible to construct a CompRowMatrix or CompColMatrix from a COO matrix (basically a list of (row,col,value) triplets)
I mean, something similar to SparseMatrix.fromCOO in https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/mllib/linalg/Matrices.scala

**Comment by fommil** [comment]
yeah, sounds like it would be pretty easy. Isn't that just the matrix market format that we already support?

feature requests are no use here, I won't have time to implement, but if you want to contribute something I'd be happy to review it.
