### ISSUE TITLE
SEGV_ACCERR when running mvn package

### ISSUE THREAD

**Issue by andrewkho** [fommil/matrix-toolkits-java#91]
Hi, I'm having trouble getting MTJ to package on _one_ of my machines. The machine runs Debian Testing and is up to date. It is a laptop Intel core i5 Ivy bridge. On my other machines, MTJ compiles and packages fine. The other machines run Debian Jessie and OSX, and they are on Intel Core2 Duo and core i7 Sandy bridge, respectively.

I am getting segfaults during some of the tests. Sometimes it will segfault during no.uib.cipr.matrix.sparse.GMRESTest, or during no.uib.cipr.matrix.sparse.GMRESILUTTest, but it always segfaults before the tests complete. On one occasion, I actually got an hs_err_pid.log file, and it indicates that there was a SEGV_ACCERR. 
[hs_err_pid13934.log.txt](https://github.com/fommil/matrix-toolkits-java/files/499056/hs_err_pid13934.log.txt)

Interestingly, if I checkout tag: mtj-1.0.3 it will package fine. But mtj-1.0.2, mtj-1.0.4, and master branch will all exhibit the same behaviour.

Have you ever seen anything like this? I actually ran a memtest86+ and found that there was a bad bit in my memory. I thought this was the issue but now I've swapped all of the RAM out for some good memory that passes memtest and I am still getting the same behaviour.

**Comment by fommil** [comment]
Sounds like you've got a broken system blas/lapack setup (netlib-java)

**Comment by andrewkho** [comment]
Dang, good catch. Turns out my alternatives were pointing to libopenblas.so.3 instead of the builtin or atlas blas. Pointing to liblapack and libblas to the atlas versions cleared it right up. Thanks!
