### ISSUE TITLE
should i check in dense complex matrix?

### ISSUE THREAD

**Issue by bobcgausa** [fommil/matrix-toolkits-java#92]
sam

i can check in complex.java, complexdensevector.java, abstractcomplexdensematrix.java, complexdensematrix.java
matrix representation is column order array as with your dense matrix
but not much point if z routines not added to fommil.

i am a programmer, not a math guy, but will maintain and extend code on request.
let me know if i should proceed.
bob cook
professorcook.org

**Comment by fommil** [comment]
Hi Bob, it probably doesn't make sense to extend MTJ for complex numbers at. this stage. I think you mean netlib-java needs Z support? And I agree, but I need funding to spend any time on that as I have no free time.

**Comment by bobcgausa** [comment]
i understand.
let me know when you get funding.
bobcook47@hotmail.com

**Comment by fommil** [comment]
@bobcgausa thanks for offering with the complex routines. Perhaps you could create an mtj-extras project or something that I could link to from here?

BTW, I doubt I'll ever get the funding... the Apache projects are using netlib-java extensively but they think of "free software" as "free labour" whereas I'm more about "free / libre software". And I don't use this project at work anymore.
