### ISSUE TITLE
No speeding up on Sparse Matrix multiplication 

### ISSUE THREAD

**Issue by hack1nt0** [fommil/matrix-toolkits-java#94]
When I doing a multiplication of Sparse Matrix(59071 * 548561, of 10379254 no zero entries) and a Dense Matrix. The code using MTJ is much slower(not ever stopping) than the pure java implementation. 

Also tried the LinkedSparseMatrix, but even the initialization step( using obj.set(r, c, value)) is running forever...

Working on Mac os, intel i7 4 core 2.6GHz

**Comment by fommil** [comment]
I wouldn't expect it to be faster for a matrix of that density. It's not a silver bullet.

**Comment by hack1nt0** [comment]
Got it. I am doing Text Clustering, and the Document-Term Matrix(dtm) is stored as a sparse matrix. And When using Kmeans algo, a multiplication of the dtm and centroids (the dense matrix) is critical to the overall performance.

**Comment by fommil** [comment]
if you have the memory for it, just use a dense matrix, unless you have an exceptionally regular sparse shape supported by the Templates project.

**Comment by hack1nt0** [comment]
OK, thanks for the suggestion.
