### ISSUE TITLE
SparseVector set function inserts 0 into data array

### ISSUE THREAD

**Issue by ayiyoh** [fommil/matrix-toolkits-java#95]
Can be easily reproduced like this:

		no.uib.cipr.matrix.sparse.SparseVector vector = new no.uib.cipr.matrix.sparse.SparseVector(1000);
		vector.set(767, 1);
		vector.set(938, 1);
		vector.set(895, 1);
		System.out.println("mtj indices: " + Arrays.toString(vector.getIndex()));
		System.out.println("mtj data: " + Arrays.toString(vector.getData()));

output:
                mtj indices: [767, 895, 938]
                mtj data: [1.0, 1.0, 1.0, 0.0]

It isn't the expected result, is it?

**Comment by fommil** [comment]
it's internal detail, you should only use the public API of `Vector`

**Comment by ayiyoh** [comment]
I have to use it because I was trying to convert a SparseVector from another library to MTJ, and vice versa. is it safe to do something like this when converting:
`new AnotherSparseVectorImpl(size, index, Arrays.copyOfRange(data, 0, used)) //  index, data, and used is from MTJ SparseVector`

**Comment by fommil** [comment]
if you're going to get involved with internal details, it's on **you** to decide what you consider to be "safe".

**Comment by ayiyoh** [comment]
I'll look into it. Thanks!
